[book]
title = "LapisOS documentation"
author = "Gulce"
description = "Documents for LapisOS"
src = "docs"
language = "en"
theme = "rust"

[rust]
edition = "2018"

[build]
build-dir = "book"

[output.html]
git-repository-url="https://github.com/lapis-org/docs"
site-url="https://lapis-org.github.io/docs"