[book]
title = "Violet documentation"
author = "Gulce"
description = "Future — Powered by Violet, designed for You."
src = "docs"
language = "en"
theme = "rust"

[rust]
edition = "2018"

[build]
build-dir = "book"

[output.html]
theme = "violet-theme"
default-theme = "violet"
git-repository-url="https://github.com/violet-eco/docs"
site-url="https://violet-eco.github.io/docs"
edit-url-template = "https://github.com/violet-eco/docs/edit/main/{path}"
additional-css = ["./violet-theme/violet.css", "./violet-theme/violet-highlight.css"]

[output.html.print]
enable = false